### PR TITLE
WIP: refactor: update k-bucket definition and version

### PR DESCRIPTION
**Pull request by tomonari-t**
While reading codes, I've found `k-bucket`'s type definition  can be updated.
So I've updated it and fixed type errors.

I'm confused that what type `peer` is. Please let me know if you know.
I'll add a little more type

[`_peers: Map<string, any>`](https://github.com/ethereumjs/ethereumjs-devp2p/compare/master...tomonari-t:update-k-bucket-difinition?expand=1#diff-a57e08db3fd92a095ac3d0e873dd9382R17)

### CODE REVIEW

**Comment by holgerd77** [comment]
@tomonari-t Thanks for this PR, nice 😄 , @ryanio or me should be able to give this a review soon!

**Comment by ryanio** [comment]
hey @dryajov, do you have any insight for a better type definition for `peer`?

**Comment by holgerd77** [comment]
@tomonari-t Not sure if you want to take on this job since it will likely come with some substantial extra effort, but it might be worth to consider to put something like this directly on https://github.com/DefinitelyTyped/DefinitelyTyped and remove here instead. Again, just to mention as a possibility, don't want to push in any direction, already great to have this here! 😄

**Comment by holgerd77** [comment]
Third possibility: add it to the [k-bucket](https://github.com/tristanls/k-bucket) repository

**Comment by tomonari-t** [comment]
@holgerd77 I think it is the best too and I used to do [that](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45287).
Ok, I change this PR's state to draft.

## TODO

- [ ] Add this typedef to DefinitelyTyped
- [ ] Add @types to this PR

**Comment by holgerd77** [comment]
@tomonari-t Cool! 👍  ❤️

**Comment by dryajov** [comment]
> hey @dryajov, do you have any insight for a better type definition for `peer`?

Unfortunately not, but I remember that I struggled with it in my initial refactor, and eventually gave up... I think it requires some serious deduction work in order to reconstruct it's structure correctly. Good luck :)

**Comment by holgerd77** [comment]
Hi @tomonari-t, just discovered that your types have been merged and integrated into DefinitelyTyped, congrats, wasn't aware, last time I checked PR was still open (some time ago to admit 😄 ).

I've now updated along #88 directly since changes still necessary were so small, hope this was ok.

Then I would close the PR here if you are fine with that.

**Comment by holgerd77** [comment]
Superseded by #88, will close.

**Pull request closed without merging**
