### PR TITLE
Port to typescript 2

### PR DESCRIPTION
**Pull request by dryajov**
Continuation of https://github.com/ethereumjs/ethereumjs-devp2p/pull/51

### CODE REVIEW

**Comment by dryajov** [comment]
@holgerd77 @PhilippLgh this seems to be passing now, is there anything else missing?

**Comment by holgerd77** [comment]
@PhilippLgh We don't need to directly integrate a new [Common](https://github.com/ethereumjs/ethereumjs-common) version here but can you short-term open a PR with an update on the bootnodes? Then it is at least possible to manually take over the bootnodes from there and run and test the examples here from the library.

We can then do a separate PR here integrating a new `Common` version (and likely also a few others 😄).

**Comment by holgerd77** [comment]
(or - third version - to speed things up if you are eager to merge: you can also do a local example run and just paste the result here, this just need to get through to block/tx sync in some decent amount of time)

**Comment by PhilippLgh** [comment]
Just finished the bootnode PR: https://github.com/ethereumjs/ethereumjs-common/pull/83

**Comment by PhilippLgh** [comment]
tested the examples locally with a linked updated version of ethereumjs-common and it seems to be fine... though I'm not 100% sure what output to expect

**Comment by holgerd77** [comment]
@PhilippLgh Thanks! There are still some linting errors in the example files, can you fix?

**Comment by holgerd77** [comment]
For a **release** I would suggest we give this another let's say 2 weeks of time, eventually we can target **April 15, Wednesday**, or eventually the Tuesday. Philipp wanted to give this some more maintenance work and during this time the dust can settle a bit, eventually Philipp also stumbles upon some more glitches while just using the library and doing updates and active development work.

**Comment by holgerd77** [comment]
(no totally fix date though, just as some orientation so this won't get lost again)

**Comment by PhilippLgh** [comment]
would merge this and follow the proposed two weeks game plan

**Pull request merged**
