### PR TITLE
Add support for node discovery v5

### LINKED ISSUE #19: Node discovery v5
### Introduction

Node discovery v5 is on it's way, which should make it a lot easier to discover suitable nodes. Though not standardized yet, ~it would be good to have some early experimentation/draft implementation to get closer to a feeling how the protocol (could) behave~ it would be good to have this library updated with a working implementation to support the practical usage in terms of a light client implementation.

[Here](https://github.com/fjl/p2p-drafts) are some draft documents on this. Also valuable in this regard: [Talk](https://www.youtube.com/watch?v=YqGncHRtshM) from Felix at Devcon3.

Current ``py-evm`` implementation work: https://github.com/ethereum/py-evm/pull/209

### Current Situation

Currently the library supports [Node discovery v4](https://github.com/ethereum/devp2p/blob/master/discv4.md) implemented in ``src/dpt``, where [kbucket.js](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/src/dpt/kbucket.js) manages the list of peers in a ``Kademlia``-like DHT, [message.js](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/src/dpt/message.js) implements the different message types like ``ping``, ``pong`` or ``neighbours`` to discover new peers and [server.js](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/src/dpt/server.js) sets up a server to handle the discovery communication.

There are static tests for the message types in [./test/dpt-message.js](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/test/dpt-message.js), the integrated communication process is tested in [./test/integration/dpt-simulator.js](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/test/integration/dpt-simulator.js) as well as the corresponding ``eth`` and ``les`` files.

With the two ``peer-communication`` example scripts in the ``examples`` folder both ``ETH`` and ``LES`` (so full- and light client wire) communication can be tested in a real-world scenario by connecting to an actual network of in-production clients.

### Task Description

Node discovery v5 updated the structure of [Node records](https://github.com/fjl/p2p-drafts/blob/master/discv5-enr.md), brings changes to the communication flow by adding new [packet types](https://github.com/fjl/p2p-drafts/blob/master/discv5-packets.md) and introduces the concept of [topics](https://github.com/fjl/p2p-drafts/blob/master/discv5-topics.md) for exchanging on the capability of peers.

A first step into this task would be to work out some concept/idea where these additional/changed components fit into the existing v4 implementation and where current files/classes can be extended and where additional structures have to be set up. Since network communication implementation is very error-prone it will probably ease implementation to early on think along how to extend existing tests and add new tests for added functionality.

### Goals

Though being still marked as "experimental" Geth has a working v5 discovery implementation for some time. Sufficient requirement for this issue to be completed is a working ``peer-communication`` example where it is possible to set the discovery to ``v5`` - e.g. by CL parameter or example internal constant - and get a working ``LES`` and/or (optimally both) ``ETH`` connection (working means here: e.g. ``LES`` packets are actually passed through) in a reasonable amount of time (repeatedly < 5 min until first connection occurs).

Necessary side goals are:

- An extended code base which...
  - follows the style principles and coding best practices of the existing code base
  - is readable/maintainable for other developers
  - introduces no or minimal code repetitions
- An extended test suite which keeps code coverage [for the DHT](https://coveralls.io/github/ethereumjs/ethereumjs-devp2p) on more-or-less the current level
- Some additions to the ``README`` docs which gives some usage guides and reflect the API changes

### Required Skills

Everyone is invited to join and take on this task. Since this an advanced task requiring deeper knowledge of the Ethereum networking stack it is probably more likely that you succeed if you bring along skills/experience in the following fields:

- Experience with working on larger code bases in Node.js/modern ``ES6`` Javascript
- Experience with the Node.js toolchain / ecosystem
- Knowledge/understanding of generic p2p networking concepts
- Some understanding of the Ethereum networking mechanics
- Experience with assuring code quality/testing

### Guidance

For questions helping to understand the existing code base and the scope of this issue you will get active guidance by the creator of this issue (@holgerd77, EthereumJS team).

### PR DESCRIPTION
**Pull request by tcsiwula**
### WIP: Please do not merge yet

Fixes #19.

# Issue update for node discovery v5 
Completion status: **~46%** 
Today's date:  **Saturday August 25th 2018**
Target finish date:  **Monday September 3rd 2018**
Task break down: ~46% = [6.5 / 14] = [ ((4 ✅ + (3🚧/2)) ) / (14✅🚧✖️)]
Issue: #19 
Pull request: #42 

### Structural tasks
| Task name | Implemented | Task Description |
| ---------- | --------- | --------------------------------------------------- |
| node records | ✖️ No | add **node records** support for node discovery v5 |
| packet types | 🚧 [Wip](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-ac6106e15ebadc071bd9547999ca99f8R171) | add **packet types** support for node discovery v5 |
| topics | 🚧 [Wip](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-ac6106e15ebadc071bd9547999ca99f8R212) | add **topics** support for node discovery v5 |
| cli parameter	| ✅ [Yes](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R50) | add **v5 cli parameter** support for node discovery v5 |
| documentation	| ✅ [Yes](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-04c6e90faac2675aa89e2176d2eec7d8R65) | add **v5 cli parameter** support for node discovery v5 |

### Version 5 demo example tasks
| Demo name    									| Implemented 		|
| ------------ 									| ----------- 		|
| peer-communication-v5.js 			| 🚧 [Wip](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-0e485afc4851da7ac9a6c01aff970800R5)  |
| peer-communication-les-v5.js 	| ✖️ No |

### New test coverage tasks
| Test name    | Implemented | Test Description                                   |
| ------------ | ----------- | -------------------------------------------------- |
| dpt-message-v5.js 			| ✖️ No  | static tests for v5 message types, node records, topics |
| dpt-simulator-v5.js | ✖️ No  | dpt integration communication tests for v5 |
| eth-simulator-v5.js | ✖️ No  | eth integration communication tests for v5 |
| les-simulator-v5.js | ✖️ No  | les integration communication tests for v5 |
| util.js | ✅ [Yes](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-a67f68d9ce269d1d38412c422177fecbR33) |

### Pass existing tests, style, coverage
| Name    		 | Passing 				|
| ------------ | ----------- 		|
| coveralls    | ✖️ [No](https://coveralls.io/builds/18662368)      		|
| travis       | ✅ [Yes](https://travis-ci.org/ethereumjs/ethereumjs-devp2p/jobs/420338356)      |

## almost there 😀
Alt Text

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi Tim, cool, that already looks like a substantial amount of work and additions, happy to see the progress! Will think about the testing questions, can't promise though that I will make it today.

Let's not over-rush now in the other direction 😄 , you can really take your time, I would actually prefer a bit if this can ripen a bit during 2-3 weeks of ongoing work. Of course this also depends on the time-slots you can set free.

Anyway, cool to see progress here!

**Comment by holgerd77** [comment]
Hi Tim, can you make ``version`` an option in [dpt/server.js](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/dpt/server.js) - probably defaulting to ``0x04`` if not provided, remove the ``VERSION`` constant and then do appropriate switches depending on what version someone chooses to initialize the server with?

For testing you should probably be able to build upon the [integration](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/test/integration) tests and extend the ``DPT`` setup in [integration/util.js](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/test/integration/util.js) with possibilities to either instantiate a v4 or v5 setup (or a mixed one? 😄 ) and then add some tests to the [integration/dpt-simulator.js](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/test/integration/dpt-simulator.js) file who should behave like they should behave 😸 ).

Not sure if this is enough for tests but that would be a start, does this makes sense or do I miss something? Maybe also start early with this since according to my experience especially on the devp2p library having some tests makes further development a lot easier.

**Comment by tcsiwula** [comment]
Awesome sounds good. Yeah, baby steps! Sure thing, will have a bunch of free time this weekend. Good call on the cli args for versioning, that ran through my mind, will add!

**Comment by holgerd77** [comment]
@tcsiwula Just to make sure that there is no misunderstanding: ``version`` should be an option for the constructor in ``server.js``, so ``options.version``. This can of course be used from CLI but also in other programmatic contexts.

**Comment by tcsiwula** [comment]
Hey @holgerd77 how is your linting working for the CI or whatever? I saw there was a ``` "standard": {
    "parser": "babel-eslint"
  }``` though not to sure how to get this working or auto detecting with my ide.

**Comment by holgerd77** [comment]
@tcsiwula Just run ``npm run lint`` for checking.

**Comment by tcsiwula** [comment]
What about for fixing my linting errors? Running: 
```
eslint --fix src

Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

``` 
.
Should I make a ```.eslint``` config or how should I handle this and what settings?

**Comment by holgerd77** [comment]
Just temporarily add "--fix" to the standard lint command in package.json and fix the remaining ones manually.

**Comment by tcsiwula** [comment]
# Issue update for node discovery v5 
Completion status: **~46%** 
Today's date:  **Saturday August 25th 2018**
Target finish date:  **Monday September 3rd 2018**
Task break down: ~46% = [6.5 / 14] = [ ((4 ✅ + (3🚧/2)) ) / (14✅🚧✖️)]
Issue: #19 
Pull request: #42 

### Structural tasks
| Task name | Implemented | Task Description |
| ---------- | --------- | --------------------------------------------------- |
| node records | ✖️ No | add **node records** support for node discovery v5 |
| packet types | 🚧 [Wip](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-ac6106e15ebadc071bd9547999ca99f8R171) | add **packet types** support for node discovery v5 |
| topics | 🚧 [Wip](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-ac6106e15ebadc071bd9547999ca99f8R212) | add **topics** support for node discovery v5 |
| cli parameter	| ✅ [Yes](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R50) | add **v5 cli parameter** support for node discovery v5 |
| documentation	| ✅ [Yes](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-04c6e90faac2675aa89e2176d2eec7d8R65) | add **v5 cli parameter** support for node discovery v5 |

### Version 5 demo example tasks
| Demo name    									| Implemented 		|
| ------------ 									| ----------- 		|
| peer-communication-v5.js 			| 🚧 [Wip](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-0e485afc4851da7ac9a6c01aff970800R5)  |
| peer-communication-les-v5.js 	| ✖️ No |

### New test coverage tasks
| Test name    | Implemented | Test Description                                   |
| ------------ | ----------- | -------------------------------------------------- |
| dpt-message-v5.js 			| ✖️ No  | static tests for v5 message types, node records, topics |
| dpt-simulator-v5.js | ✖️ No  | dpt integration communication tests for v5 |
| eth-simulator-v5.js | ✖️ No  | eth integration communication tests for v5 |
| les-simulator-v5.js | ✖️ No  | les integration communication tests for v5 |
| util.js | ✅ [Yes](https://github.com/ethereumjs/ethereumjs-devp2p/pull/42/files#diff-a67f68d9ce269d1d38412c422177fecbR33) |

### Pass existing tests, style, coverage
| Name    		 | Passing 				|
| ------------ | ----------- 		|
| coveralls    | ✖️ [No](https://coveralls.io/builds/18662368)      		|
| travis       | ✅ [Yes](https://travis-ci.org/ethereumjs/ethereumjs-devp2p/jobs/420338356)      |

## update next on monday 😀
Alt Text

**Comment by fjl** [comment]
It's best if you start with node records. The actual v5 protocol in geth is a temporary placeholder.

**Comment by tcsiwula** [comment]
@fjl thanks for the heads up, sounds good ^_^

**Comment by fjl** [comment]
@tcsiwula There is now a tracking issue for the actual protocol spec. Let's discuss there :).

**Comment by holgerd77** [comment]
Hi @tcsiwula, thanks for all the active engagement in the direct protocol discussion with @fjl, I am also realizing that this is much more a work-in-progress spec than I thought. I would nevertheless try to see that we find some clean finish for this bounty PR, so that we don't have to carry this into 2019. 😛

Do you think it's realistic to get to a point where we have a somewhat complete version of a currently consistent draft state of the protocol implemented, or - if this is still too much work left - can't judge at the moment: do you see a consistent set of subfeatures/-parts that can be finished implementing, so that

a) tests are running and
b) this doesn't prevent the old protocol v4 version from running

(that would be the base conditions I could think of now, feel free to add).

Best
Holger

**Comment by tcsiwula** [comment]
Succeeded by new PR #48 allowing administrative access & direct collaborator [branch discovery-v5](https://github.com/ethereumjs/ethereumjs-devp2p/tree/discovery-v5)

**Pull request closed without merging**
